### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by csim063** [r-spatialecology/spectre#27]
Not sure where exactly to put this (guess that's why they have the Kanban but hey).

This is a summary of what still needs to be done from my point of view.

- [ ] Improve the optimisation algorithm (I have listed the ideas I have thought of but if you have any please add and implement)
  - [ ] Select the columns with the lowest relatedness to target preferentially
  - [ ] Weight the species selection for the creation of the initial solution matrix
  - [ ] Allow users to include actual site data

- [ ] Finalise the package
  - [ ] Implement testing @mhesselbarth 
  - [ ] Write documentation
  - [ ] Submit to CRAN

- [ ] Run the example analyses @csim063 
  - [x] Parse out the presence/absence data from ebirds (hopefully with related environmental measures)
  - [x] Get environmental predictor rasters
  - [x] Calculate alpha and beta models
  - [ ] Run optimisation
  - [ ] Write vignette

- [ ] Write and submit a paper @csim063
