### ISSUE TITLE
CRAN submission checklist

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/spectre#94]
Checklist for CRAN submission: 

- [x] Check which packages we need as imports and suggests (also due to `testthat`; related to #76)
- [x] Check R CMD Check on several OS 
- [x] Missing information DESCRIPTION (Authors, Maintainer, Description)
- [x] Check Winbuilder once we have maintainer (`devtools::check_win_release()`; `devtools::check_win_devel()`)
- [x] Update NEWS.md
- [x] Update cran-comments.md
- [x] Update readme
- [x] Change title to  ‘Predict Regional Community Composition’ (capitalize)

**Comment by mhesselbarth** [comment]
On Solaris
```
test-minconf.cpp: In function ‘void testthat_disabled_test_60()’:
test-minconf.cpp:95:69: error: ‘Approx’ was not declared in this scope
     expect_true(mc.test_calc_error(commonness, target) == Approx(0.0));
                                                                     ^
/home/ripley/R/Lib32/testthat/include/testthat/testthat.h:184:49: note: in definition of macro ‘expect_true’
 # define expect_true(__X__)             (void) (__X__)
                                                 ^
*** Error code 1
make: Fatal error: Command failed for target `test-minconf.o'
```
